.PHONY: clean

TOCK_USERLAND_BASE_DIR ?= ../libtock-c

SRC_DIR = $(TOCK_USERLAND_BASE_DIR)/../libents/src/libents

NANOPB_DIR = $(SRC_DIR)/nanopb

all: $(NANOPB_DIR)/README.md

clean::
	rm -rf build

# confirm nanopb is checked out
$(NANOPB_DIR)/README.md:
	git submodule update --init -- $(NANOPB_DIR)

