.PHONY: clean

TOCK_USERLAND_BASE_DIR ?= ../libtock-c


all: $(TOCK_USERLAND_BASE_DIR)/../libents/nanopb/README.md

clean::
	rm -rf build

# confirm RadioLib git submodule is checked out. 
$(TOCK_USERLAND_BASE_DIR)/../nanopb/nanopb/README.md:
	git submodule update --init -- $(TOCK_USERLAND_BASE_DIR)/../libents/nanopb

