/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "controller.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(Esp32Command, Esp32Command, 2)


PB_BIND(PageCommand, PageCommand, AUTO)


PB_BIND(TestCommand, TestCommand, AUTO)


PB_BIND(WiFiCommand, WiFiCommand, 2)


PB_BIND(UserConfigCommand, UserConfigCommand, 2)


PB_BIND(MicroSDCommand, MicroSDCommand, 2)


PB_BIND(IrrigationCommand, IrrigationCommand, AUTO)


PB_BIND(PowerCommand, PowerCommand, AUTO)























