/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_USER_CONFIG_PB_H_INCLUDED
#define PB_USER_CONFIG_PB_H_INCLUDED
#include "../nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _EnabledSensor {
    EnabledSensor_Voltage = 0,
    EnabledSensor_Current = 1,
    EnabledSensor_Teros12 = 2,
    EnabledSensor_Teros21 = 3,
    EnabledSensor_BME280 = 4,
    EnabledSensor_Phytos31 = 5,
    EnabledSensor_SEN0308 = 6,
    EnabledSensor_SEN0257 = 7,
    EnabledSensor_YFS210C = 8,
    EnabledSensor_PCAP02 = 9
} EnabledSensor;

typedef enum _Uploadmethod {
    Uploadmethod_LoRa = 0,
    Uploadmethod_WiFi = 1
} Uploadmethod;

/* Struct definitions */
typedef struct _UserConfiguration {
    /* ********* Upload Settings ********* */
    uint32_t logger_id; /* id of the logging device */
    uint32_t cell_id; /* id of the cell measured */
    Uploadmethod Upload_method; /* indicates whether LoRa or WiFi is used */
    uint32_t Upload_interval; /* upload time in seconds */
    /* ********* Measurement Settings ********* */
    pb_size_t enabled_sensors_count;
    EnabledSensor enabled_sensors[5]; /* List of enabled sensors */
    double Voltage_Slope; /* Calibration slope for voltage */
    double Voltage_Offset; /* Calibration offset for voltage */
    double Current_Slope; /* Calibration slope for current */
    double Current_Offset; /* Calibration offset for current */
    /* ********* WiFi Settings ********* */
    char WiFi_SSID[33];
    char WiFi_Password[65];
    char API_Endpoint_URL[65];
    /* Deprecated
 Embedded into the endpoint URL */
    uint32_t API_Endpoint_Port;
} UserConfiguration;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _EnabledSensor_MIN EnabledSensor_Voltage
#define _EnabledSensor_MAX EnabledSensor_PCAP02
#define _EnabledSensor_ARRAYSIZE ((EnabledSensor)(EnabledSensor_PCAP02+1))

#define _Uploadmethod_MIN Uploadmethod_LoRa
#define _Uploadmethod_MAX Uploadmethod_WiFi
#define _Uploadmethod_ARRAYSIZE ((Uploadmethod)(Uploadmethod_WiFi+1))

#define UserConfiguration_Upload_method_ENUMTYPE Uploadmethod
#define UserConfiguration_enabled_sensors_ENUMTYPE EnabledSensor


/* Initializer values for message structs */
#define UserConfiguration_init_default           {0, 0, _Uploadmethod_MIN, 0, 0, {_EnabledSensor_MIN, _EnabledSensor_MIN, _EnabledSensor_MIN, _EnabledSensor_MIN, _EnabledSensor_MIN}, 0, 0, 0, 0, "", "", "", 0}
#define UserConfiguration_init_zero              {0, 0, _Uploadmethod_MIN, 0, 0, {_EnabledSensor_MIN, _EnabledSensor_MIN, _EnabledSensor_MIN, _EnabledSensor_MIN, _EnabledSensor_MIN}, 0, 0, 0, 0, "", "", "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define UserConfiguration_logger_id_tag          1
#define UserConfiguration_cell_id_tag            2
#define UserConfiguration_Upload_method_tag      3
#define UserConfiguration_Upload_interval_tag    4
#define UserConfiguration_enabled_sensors_tag    5
#define UserConfiguration_Voltage_Slope_tag      6
#define UserConfiguration_Voltage_Offset_tag     7
#define UserConfiguration_Current_Slope_tag      8
#define UserConfiguration_Current_Offset_tag     9
#define UserConfiguration_WiFi_SSID_tag          10
#define UserConfiguration_WiFi_Password_tag      11
#define UserConfiguration_API_Endpoint_URL_tag   12
#define UserConfiguration_API_Endpoint_Port_tag  13

/* Struct field encoding specification for nanopb */
#define UserConfiguration_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   logger_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   cell_id,           2) \
X(a, STATIC,   SINGULAR, UENUM,    Upload_method,     3) \
X(a, STATIC,   SINGULAR, UINT32,   Upload_interval,   4) \
X(a, STATIC,   REPEATED, UENUM,    enabled_sensors,   5) \
X(a, STATIC,   SINGULAR, DOUBLE,   Voltage_Slope,     6) \
X(a, STATIC,   SINGULAR, DOUBLE,   Voltage_Offset,    7) \
X(a, STATIC,   SINGULAR, DOUBLE,   Current_Slope,     8) \
X(a, STATIC,   SINGULAR, DOUBLE,   Current_Offset,    9) \
X(a, STATIC,   SINGULAR, STRING,   WiFi_SSID,        10) \
X(a, STATIC,   SINGULAR, STRING,   WiFi_Password,    11) \
X(a, STATIC,   SINGULAR, STRING,   API_Endpoint_URL,  12) \
X(a, STATIC,   SINGULAR, UINT32,   API_Endpoint_Port,  13)
#define UserConfiguration_CALLBACK NULL
#define UserConfiguration_DEFAULT NULL

extern const pb_msgdesc_t UserConfiguration_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define UserConfiguration_fields &UserConfiguration_msg

/* Maximum encoded size of messages (where known) */
#define USER_CONFIG_PB_H_MAX_SIZE                UserConfiguration_size
#define UserConfiguration_size                   238

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
