/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_CONTROLLER_PB_H_INCLUDED
#define PB_CONTROLLER_PB_H_INCLUDED
#include "../nanopb/pb.h"
#include "user_config.pb.h"
#include "measurements.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Type of request */
typedef enum _PageCommand_RequestType {
    PageCommand_RequestType_OPEN = 0,
    PageCommand_RequestType_CLOSE = 1,
    PageCommand_RequestType_READ = 2,
    PageCommand_RequestType_WRITE = 3
} PageCommand_RequestType;

typedef enum _TestCommand_ChangeState {
    /* Data is received by the module */
    TestCommand_ChangeState_RECEIVE = 0,
    /* Data is received by the module indicating data for subsequent request */
    TestCommand_ChangeState_RECEIVE_REQUEST = 1,
    /* Data is sent my the module */
    TestCommand_ChangeState_REQUEST = 2
} TestCommand_ChangeState;

typedef enum _WiFiCommand_Type {
    /* Connect to WiFi network */
    WiFiCommand_Type_CONNECT = 0,
    /* Post data to endpoint */
    WiFiCommand_Type_POST = 1,
    /* Check HTTP code and response from POST */
    WiFiCommand_Type_CHECK = 2,
    /* Timesync request */
    WiFiCommand_Type_TIME = 3,
    /* Disconnect from WiFi network */
    WiFiCommand_Type_DISCONNECT = 4,
    /* Get WiFi status */
    WiFiCommand_Type_CHECK_WIFI = 5,
    /* Check connectivity to API */
    WiFiCommand_Type_CHECK_API = 6,
    /* Force NTP sync */
    WiFiCommand_Type_NTP_SYNC = 7,
    /* Host a WiFi network */
    WiFiCommand_Type_HOST = 8,
    /* Stop hosting a WiFi network */
    WiFiCommand_Type_STOP_HOST = 9,
    /* Get host info */
    WiFiCommand_Type_HOST_INFO = 10
} WiFiCommand_Type;

typedef enum _UserConfigCommand_RequestType {
    /* controller requests config from target */
    UserConfigCommand_RequestType_REQUEST_CONFIG = 0,
    /* controller sends config to target */
    UserConfigCommand_RequestType_RESPONSE_CONFIG = 1,
    /* starts the user config webserver */
    UserConfigCommand_RequestType_START = 2
} UserConfigCommand_RequestType;

typedef enum _MicroSDCommand_Type {
    /* Decode and save data to a CSV file on the microSD card */
    MicroSDCommand_Type_SAVE = 0,
    /* Send UserConfig for CSV header creation */
    MicroSDCommand_Type_USERCONFIG = 1
} MicroSDCommand_Type;

typedef enum _MicroSDCommand_ReturnCode {
    MicroSDCommand_ReturnCode_SUCCESS = 0,
    MicroSDCommand_ReturnCode_ERROR_GENERAL = 1,
    MicroSDCommand_ReturnCode_ERROR_MICROSD_NOT_INSERTED = 2,
    MicroSDCommand_ReturnCode_ERROR_FILE_SYSTEM_NOT_MOUNTABLE = 3,
    MicroSDCommand_ReturnCode_ERROR_PAYLOAD_NOT_DECODED = 4,
    MicroSDCommand_ReturnCode_ERROR_FILE_NOT_OPENED = 5
} MicroSDCommand_ReturnCode;

typedef enum _IrrigationCommand_Type {
    IrrigationCommand_Type_CHECK = 0
} IrrigationCommand_Type;

typedef enum _IrrigationCommand_State {
    /* needs to be opened to prevent open defined twice */
    IrrigationCommand_State_OPEN = 0,
    IrrigationCommand_State_CLOSE = 1
} IrrigationCommand_State;

typedef enum _PowerCommand_Type {
    /* Put the device to sleep */
    PowerCommand_Type_SLEEP = 0,
    /* Check functionality after wakeup */
    PowerCommand_Type_WAKEUP = 1
} PowerCommand_Type;

/* copied from idf library */
typedef enum _PowerCommand_WakeupReason {
    PowerCommand_WakeupReason_POWER_WAKEUP_EXT0 = 0,
    PowerCommand_WakeupReason_POWER_WAKEUP_EXT1 = 1,
    PowerCommand_WakeupReason_POWER_WAKEUP_TIMER = 2,
    PowerCommand_WakeupReason_POWER_WAKEUP_TOUCHPAD = 3,
    PowerCommand_WakeupReason_POWER_WAKEUP_ULP = 4,
    PowerCommand_WakeupReason_POWER_WAKEUP_GPIO = 5,
    PowerCommand_WakeupReason_POWER_WAKEUP_UART = 6,
    PowerCommand_WakeupReason_POWER_WAKEUP_WIFI = 7,
    PowerCommand_WakeupReason_POWER_WAKEUP_COCPU = 8,
    PowerCommand_WakeupReason_POWER_WAKEUP_COCPU_TRAP_TRIG = 9,
    PowerCommand_WakeupReason_POWER_WAKEUP_BT = 10
} PowerCommand_WakeupReason;

/* Struct definitions */
typedef struct _PageCommand {
    /* File request type */
    PageCommand_RequestType file_request;
    /* Integer for file descriptor */
    uint32_t file_descriptor;
    /* Block size of read/write */
    uint32_t block_size;
    /* Number of bytes */
    uint32_t num_bytes;
} PageCommand;

typedef struct _TestCommand {
    /* State to put module into */
    TestCommand_ChangeState state;
    /* Data field for test command data */
    int32_t data;
} TestCommand;

typedef PB_BYTES_ARRAY_T(222) WiFiCommand_resp_t;
typedef struct _WiFiCommand {
    /* Command type */
    WiFiCommand_Type type;
    /* WiFI SSID */
    char ssid[33];
    /* WiFi Password */
    char passwd[65];
    /* Endpoint url */
    char url[257];
    /* Return code */
    uint32_t rc;
    /* Timestamp n unix epochs */
    uint32_t ts;
    /* binary data response */
    WiFiCommand_resp_t resp;
    /* Port */
    uint32_t port;
    /* MAC address */
    char mac[18];
    /* Number of connected devices */
    uint32_t clients;
} WiFiCommand;

typedef struct _UserConfigCommand {
    /* type of command */
    UserConfigCommand_RequestType type;
    /* configuration data */
    bool has_config_data;
    UserConfiguration config_data;
} UserConfigCommand;

typedef struct _MicroSDCommand {
    /* Command type */
    MicroSDCommand_Type type;
    /* Filename */
    char filename[256];
    /* Return code */
    MicroSDCommand_ReturnCode rc;
    pb_size_t which_data;
    union {
        /* measurement to be saved */
        Measurement meas;
        /* userConfig to be saved */
        UserConfiguration uc;
    } data;
} MicroSDCommand;

typedef struct _IrrigationCommand {
    IrrigationCommand_Type type;
    IrrigationCommand_State state;
} IrrigationCommand;

typedef struct _PowerCommand {
    PowerCommand_Type type;
    PowerCommand_WakeupReason reason;
    uint32_t boot_count;
} PowerCommand;

typedef struct _Esp32Command {
    pb_size_t which_command;
    union {
        PageCommand page_command;
        TestCommand test_command;
        WiFiCommand wifi_command;
        MicroSDCommand microsd_command;
        IrrigationCommand irrigation_command;
        UserConfigCommand user_config_command;
        PowerCommand power_command;
    } command;
} Esp32Command;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _PageCommand_RequestType_MIN PageCommand_RequestType_OPEN
#define _PageCommand_RequestType_MAX PageCommand_RequestType_WRITE
#define _PageCommand_RequestType_ARRAYSIZE ((PageCommand_RequestType)(PageCommand_RequestType_WRITE+1))

#define _TestCommand_ChangeState_MIN TestCommand_ChangeState_RECEIVE
#define _TestCommand_ChangeState_MAX TestCommand_ChangeState_REQUEST
#define _TestCommand_ChangeState_ARRAYSIZE ((TestCommand_ChangeState)(TestCommand_ChangeState_REQUEST+1))

#define _WiFiCommand_Type_MIN WiFiCommand_Type_CONNECT
#define _WiFiCommand_Type_MAX WiFiCommand_Type_HOST_INFO
#define _WiFiCommand_Type_ARRAYSIZE ((WiFiCommand_Type)(WiFiCommand_Type_HOST_INFO+1))

#define _UserConfigCommand_RequestType_MIN UserConfigCommand_RequestType_REQUEST_CONFIG
#define _UserConfigCommand_RequestType_MAX UserConfigCommand_RequestType_START
#define _UserConfigCommand_RequestType_ARRAYSIZE ((UserConfigCommand_RequestType)(UserConfigCommand_RequestType_START+1))

#define _MicroSDCommand_Type_MIN MicroSDCommand_Type_SAVE
#define _MicroSDCommand_Type_MAX MicroSDCommand_Type_USERCONFIG
#define _MicroSDCommand_Type_ARRAYSIZE ((MicroSDCommand_Type)(MicroSDCommand_Type_USERCONFIG+1))

#define _MicroSDCommand_ReturnCode_MIN MicroSDCommand_ReturnCode_SUCCESS
#define _MicroSDCommand_ReturnCode_MAX MicroSDCommand_ReturnCode_ERROR_FILE_NOT_OPENED
#define _MicroSDCommand_ReturnCode_ARRAYSIZE ((MicroSDCommand_ReturnCode)(MicroSDCommand_ReturnCode_ERROR_FILE_NOT_OPENED+1))

#define _IrrigationCommand_Type_MIN IrrigationCommand_Type_CHECK
#define _IrrigationCommand_Type_MAX IrrigationCommand_Type_CHECK
#define _IrrigationCommand_Type_ARRAYSIZE ((IrrigationCommand_Type)(IrrigationCommand_Type_CHECK+1))

#define _IrrigationCommand_State_MIN IrrigationCommand_State_OPEN
#define _IrrigationCommand_State_MAX IrrigationCommand_State_CLOSE
#define _IrrigationCommand_State_ARRAYSIZE ((IrrigationCommand_State)(IrrigationCommand_State_CLOSE+1))

#define _PowerCommand_Type_MIN PowerCommand_Type_SLEEP
#define _PowerCommand_Type_MAX PowerCommand_Type_WAKEUP
#define _PowerCommand_Type_ARRAYSIZE ((PowerCommand_Type)(PowerCommand_Type_WAKEUP+1))

#define _PowerCommand_WakeupReason_MIN PowerCommand_WakeupReason_POWER_WAKEUP_EXT0
#define _PowerCommand_WakeupReason_MAX PowerCommand_WakeupReason_POWER_WAKEUP_BT
#define _PowerCommand_WakeupReason_ARRAYSIZE ((PowerCommand_WakeupReason)(PowerCommand_WakeupReason_POWER_WAKEUP_BT+1))


#define PageCommand_file_request_ENUMTYPE PageCommand_RequestType

#define TestCommand_state_ENUMTYPE TestCommand_ChangeState

#define WiFiCommand_type_ENUMTYPE WiFiCommand_Type

#define UserConfigCommand_type_ENUMTYPE UserConfigCommand_RequestType

#define MicroSDCommand_type_ENUMTYPE MicroSDCommand_Type
#define MicroSDCommand_rc_ENUMTYPE MicroSDCommand_ReturnCode

#define IrrigationCommand_type_ENUMTYPE IrrigationCommand_Type
#define IrrigationCommand_state_ENUMTYPE IrrigationCommand_State

#define PowerCommand_type_ENUMTYPE PowerCommand_Type
#define PowerCommand_reason_ENUMTYPE PowerCommand_WakeupReason


/* Initializer values for message structs */
#define Esp32Command_init_default                {0, {PageCommand_init_default}}
#define PageCommand_init_default                 {_PageCommand_RequestType_MIN, 0, 0, 0}
#define TestCommand_init_default                 {_TestCommand_ChangeState_MIN, 0}
#define WiFiCommand_init_default                 {_WiFiCommand_Type_MIN, "", "", "", 0, 0, {0, {0}}, 0, "", 0}
#define UserConfigCommand_init_default           {_UserConfigCommand_RequestType_MIN, false, UserConfiguration_init_default}
#define MicroSDCommand_init_default              {_MicroSDCommand_Type_MIN, "", _MicroSDCommand_ReturnCode_MIN, 0, {Measurement_init_default}}
#define IrrigationCommand_init_default           {_IrrigationCommand_Type_MIN, _IrrigationCommand_State_MIN}
#define PowerCommand_init_default                {_PowerCommand_Type_MIN, _PowerCommand_WakeupReason_MIN, 0}
#define Esp32Command_init_zero                   {0, {PageCommand_init_zero}}
#define PageCommand_init_zero                    {_PageCommand_RequestType_MIN, 0, 0, 0}
#define TestCommand_init_zero                    {_TestCommand_ChangeState_MIN, 0}
#define WiFiCommand_init_zero                    {_WiFiCommand_Type_MIN, "", "", "", 0, 0, {0, {0}}, 0, "", 0}
#define UserConfigCommand_init_zero              {_UserConfigCommand_RequestType_MIN, false, UserConfiguration_init_zero}
#define MicroSDCommand_init_zero                 {_MicroSDCommand_Type_MIN, "", _MicroSDCommand_ReturnCode_MIN, 0, {Measurement_init_zero}}
#define IrrigationCommand_init_zero              {_IrrigationCommand_Type_MIN, _IrrigationCommand_State_MIN}
#define PowerCommand_init_zero                   {_PowerCommand_Type_MIN, _PowerCommand_WakeupReason_MIN, 0}

/* Field tags (for use in manual encoding/decoding) */
#define PageCommand_file_request_tag             1
#define PageCommand_file_descriptor_tag          2
#define PageCommand_block_size_tag               3
#define PageCommand_num_bytes_tag                4
#define TestCommand_state_tag                    1
#define TestCommand_data_tag                     2
#define WiFiCommand_type_tag                     1
#define WiFiCommand_ssid_tag                     2
#define WiFiCommand_passwd_tag                   3
#define WiFiCommand_url_tag                      4
#define WiFiCommand_rc_tag                       5
#define WiFiCommand_ts_tag                       6
#define WiFiCommand_resp_tag                     7
#define WiFiCommand_port_tag                     8
#define WiFiCommand_mac_tag                      9
#define WiFiCommand_clients_tag                  10
#define UserConfigCommand_type_tag               1
#define UserConfigCommand_config_data_tag        2
#define MicroSDCommand_type_tag                  1
#define MicroSDCommand_filename_tag              2
#define MicroSDCommand_rc_tag                    3
#define MicroSDCommand_meas_tag                  4
#define MicroSDCommand_uc_tag                    5
#define IrrigationCommand_type_tag               1
#define IrrigationCommand_state_tag              2
#define PowerCommand_type_tag                    1
#define PowerCommand_reason_tag                  2
#define PowerCommand_boot_count_tag              3
#define Esp32Command_page_command_tag            1
#define Esp32Command_test_command_tag            2
#define Esp32Command_wifi_command_tag            3
#define Esp32Command_microsd_command_tag         4
#define Esp32Command_irrigation_command_tag      5
#define Esp32Command_user_config_command_tag     6
#define Esp32Command_power_command_tag           7

/* Struct field encoding specification for nanopb */
#define Esp32Command_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,page_command,command.page_command),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,test_command,command.test_command),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,wifi_command,command.wifi_command),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,microsd_command,command.microsd_command),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,irrigation_command,command.irrigation_command),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,user_config_command,command.user_config_command),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,power_command,command.power_command),   7)
#define Esp32Command_CALLBACK NULL
#define Esp32Command_DEFAULT NULL
#define Esp32Command_command_page_command_MSGTYPE PageCommand
#define Esp32Command_command_test_command_MSGTYPE TestCommand
#define Esp32Command_command_wifi_command_MSGTYPE WiFiCommand
#define Esp32Command_command_microsd_command_MSGTYPE MicroSDCommand
#define Esp32Command_command_irrigation_command_MSGTYPE IrrigationCommand
#define Esp32Command_command_user_config_command_MSGTYPE UserConfigCommand
#define Esp32Command_command_power_command_MSGTYPE PowerCommand

#define PageCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    file_request,      1) \
X(a, STATIC,   SINGULAR, UINT32,   file_descriptor,   2) \
X(a, STATIC,   SINGULAR, UINT32,   block_size,        3) \
X(a, STATIC,   SINGULAR, UINT32,   num_bytes,         4)
#define PageCommand_CALLBACK NULL
#define PageCommand_DEFAULT NULL

#define TestCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, STATIC,   SINGULAR, INT32,    data,              2)
#define TestCommand_CALLBACK NULL
#define TestCommand_DEFAULT NULL

#define WiFiCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, STRING,   ssid,              2) \
X(a, STATIC,   SINGULAR, STRING,   passwd,            3) \
X(a, STATIC,   SINGULAR, STRING,   url,               4) \
X(a, STATIC,   SINGULAR, UINT32,   rc,                5) \
X(a, STATIC,   SINGULAR, UINT32,   ts,                6) \
X(a, STATIC,   SINGULAR, BYTES,    resp,              7) \
X(a, STATIC,   SINGULAR, UINT32,   port,              8) \
X(a, STATIC,   SINGULAR, STRING,   mac,               9) \
X(a, STATIC,   SINGULAR, UINT32,   clients,          10)
#define WiFiCommand_CALLBACK NULL
#define WiFiCommand_DEFAULT NULL

#define UserConfigCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  config_data,       2)
#define UserConfigCommand_CALLBACK NULL
#define UserConfigCommand_DEFAULT NULL
#define UserConfigCommand_config_data_MSGTYPE UserConfiguration

#define MicroSDCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, STRING,   filename,          2) \
X(a, STATIC,   SINGULAR, UENUM,    rc,                3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,meas,data.meas),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (data,uc,data.uc),   5)
#define MicroSDCommand_CALLBACK NULL
#define MicroSDCommand_DEFAULT NULL
#define MicroSDCommand_data_meas_MSGTYPE Measurement
#define MicroSDCommand_data_uc_MSGTYPE UserConfiguration

#define IrrigationCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UENUM,    state,             2)
#define IrrigationCommand_CALLBACK NULL
#define IrrigationCommand_DEFAULT NULL

#define PowerCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    type,              1) \
X(a, STATIC,   SINGULAR, UENUM,    reason,            2) \
X(a, STATIC,   SINGULAR, UINT32,   boot_count,        3)
#define PowerCommand_CALLBACK NULL
#define PowerCommand_DEFAULT NULL

extern const pb_msgdesc_t Esp32Command_msg;
extern const pb_msgdesc_t PageCommand_msg;
extern const pb_msgdesc_t TestCommand_msg;
extern const pb_msgdesc_t WiFiCommand_msg;
extern const pb_msgdesc_t UserConfigCommand_msg;
extern const pb_msgdesc_t MicroSDCommand_msg;
extern const pb_msgdesc_t IrrigationCommand_msg;
extern const pb_msgdesc_t PowerCommand_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Esp32Command_fields &Esp32Command_msg
#define PageCommand_fields &PageCommand_msg
#define TestCommand_fields &TestCommand_msg
#define WiFiCommand_fields &WiFiCommand_msg
#define UserConfigCommand_fields &UserConfigCommand_msg
#define MicroSDCommand_fields &MicroSDCommand_msg
#define IrrigationCommand_fields &IrrigationCommand_msg
#define PowerCommand_fields &PowerCommand_msg

/* Maximum encoded size of messages (where known) */
#define CONTROLLER_PB_H_MAX_SIZE                 Esp32Command_size
#define Esp32Command_size                        632
#define IrrigationCommand_size                   4
#define MicroSDCommand_size                      503
#define PageCommand_size                         20
#define PowerCommand_size                        10
#define TestCommand_size                         13
#define UserConfigCommand_size                   243
#define WiFiCommand_size                         629

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
