/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_MEASUREMENTS_PB_H_INCLUDED
#define PB_MEASUREMENTS_PB_H_INCLUDED
#include "../nanopb/pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
/* Response codes from server */
typedef enum _Response_ResponseType {
    /* Data was successfully uploaded */
    Response_ResponseType_SUCCESS = 0,
    /* General Error */
    Response_ResponseType_ERROR = 1
} Response_ResponseType;

/* Struct definitions */
/* Data shared between all measurement messages */
typedef struct _MeasurementMetadata {
    /* id of the cell measured */
    uint32_t cell_id;
    /* id of the logging device */
    uint32_t logger_id;
    /* timestamp of the measurement */
    uint32_t ts;
} MeasurementMetadata;

/* *
 Power measurement message. Voltage and current can be digitially combined to
 obtain power.

 @deprecated Use individual voltage and current measurements instead.

 @see VoltageMeasurement
 @see CurrentMeasurement */
typedef struct _PowerMeasurement {
    /* voltage */
    double voltage;
    /* current */
    double current;
} PowerMeasurement;

/* * Voltage measurement with support for delta encoding */
typedef struct _VoltageDeltaMeasurement {
    uint32_t voltage;
} VoltageDeltaMeasurement;

/* * Current measurement with support for delta encoding */
typedef struct _CurrentDeltaMeasurement {
    uint32_t current;
} CurrentDeltaMeasurement;

/* * Voltage measurement */
typedef struct _VoltageMeasurement {
    double voltage;
} VoltageMeasurement;

/* * Current measurement */
typedef struct _CurrentMeasurement {
    double current;
} CurrentMeasurement;

/* *
 Power deltas measurement message. Voltage and current deltas can be
 digitially combined to obtain power.

 @deprecated Use individual voltage and current delta measurements instead.

 @see VoltageDeltaMeasurement
 @see CurrentDeltaMeasurement */
typedef struct _PowerDeltaEntry {
    uint32_t ts;
    uint32_t voltage_delta;
    uint32_t current_delta;
} PowerDeltaEntry;

/* *
 Stores power measurements for delta encoding

 @deprecated Use individual voltage and current delta measurements instead.

 @see VoltageDeltaMeasurement
 @see CurrentDeltaMeasurement */
typedef struct _PowerMeasurementDelta {
    /* voltage */
    uint32_t voltage_delta;
    /* current */
    uint32_t current_delta;
} PowerMeasurementDelta;

/* *
 Repeated delta power measurements.

 @deprecated Use RepeatedMeasurements instead.

 @see VoltageDeltaMeasurement
 @see CurrentDeltaMeasurement */
typedef struct _RepeatedPowerDeltas {
    /* Shared metadata */
    uint32_t logger_id;
    uint32_t cell_id;
    /* Repeating entries */
    pb_callback_t entries;
} RepeatedPowerDeltas;

/* Teros12 measurement message */
typedef struct _Teros12Measurement {
    /* raw volumetric water content */
    double vwc_raw;
    /* calibrated volumetric water content */
    double vwc_adj;
    /* temperature in celcious */
    double temp;
    /* electrical conductivity */
    uint32_t ec;
} Teros12Measurement;

typedef struct _Teros21Measurement {
    /* Matric potential of soil in kPa */
    double matric_pot;
    /* temperature in celcius */
    double temp;
} Teros21Measurement;

/* Phytos measurement */
typedef struct _Phytos31Measurement {
    /* raw adc voltage */
    double voltage;
    /* calibrated leaf wetness */
    double leaf_wetness;
} Phytos31Measurement;

typedef struct _BME280Measurement {
    /* pressure */
    uint32_t pressure;
    /* temperature */
    int32_t temperature;
    /* humidity */
    uint32_t humidity;
} BME280Measurement;

/* Capacitive Soil Moisture Sensor */
typedef struct _SEN0308Measurement {
    /* voltage */
    double voltage;
    /* humidity */
    double humidity;
} SEN0308Measurement;

/* Water Pressure Sensor */
typedef struct _SEN0257Measurement {
    /* voltage */
    double voltage;
    /* pressure */
    double pressure;
} SEN0257Measurement;

/* Water Flow Sensor */
typedef struct _YFS210CMeasurement {
    /* flow */
    double flow;
} YFS210CMeasurement;

/* Capacitance Sensor */
typedef struct _PCAP02Measurement {
    /* capacitance */
    double capacitance;
} PCAP02Measurement;

/* Top level measurement message */
typedef struct _Measurement {
    /* Metadata */
    bool has_meta;
    MeasurementMetadata meta;
    pb_size_t which_measurement;
    union {
        PowerMeasurement power;
        Teros12Measurement teros12;
        Phytos31Measurement phytos31;
        BME280Measurement bme280;
        Teros21Measurement teros21;
        SEN0308Measurement sen0308;
        SEN0257Measurement sen0257;
        YFS210CMeasurement yfs210c;
        PCAP02Measurement pcap02;
    } measurement;
} Measurement;

/* Acknowledge Packet */
typedef struct _Response {
    /* Response from server */
    Response_ResponseType resp;
} Response;

typedef struct _adcValue {
    uint32_t adc;
} adcValue;


#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _Response_ResponseType_MIN Response_ResponseType_SUCCESS
#define _Response_ResponseType_MAX Response_ResponseType_ERROR
#define _Response_ResponseType_ARRAYSIZE ((Response_ResponseType)(Response_ResponseType_ERROR+1))



















#define Response_resp_ENUMTYPE Response_ResponseType



/* Initializer values for message structs */
#define MeasurementMetadata_init_default         {0, 0, 0}
#define PowerMeasurement_init_default            {0, 0}
#define VoltageDeltaMeasurement_init_default     {0}
#define CurrentDeltaMeasurement_init_default     {0}
#define VoltageMeasurement_init_default          {0}
#define CurrentMeasurement_init_default          {0}
#define PowerDeltaEntry_init_default             {0, 0, 0}
#define PowerMeasurementDelta_init_default       {0, 0}
#define RepeatedPowerDeltas_init_default         {0, 0, {{NULL}, NULL}}
#define Teros12Measurement_init_default          {0, 0, 0, 0}
#define Teros21Measurement_init_default          {0, 0}
#define Phytos31Measurement_init_default         {0, 0}
#define BME280Measurement_init_default           {0, 0, 0}
#define SEN0308Measurement_init_default          {0, 0}
#define SEN0257Measurement_init_default          {0, 0}
#define YFS210CMeasurement_init_default          {0}
#define PCAP02Measurement_init_default           {0}
#define Measurement_init_default                 {false, MeasurementMetadata_init_default, 0, {PowerMeasurement_init_default}}
#define Response_init_default                    {_Response_ResponseType_MIN}
#define adcValue_init_default                    {0}
#define MeasurementMetadata_init_zero            {0, 0, 0}
#define PowerMeasurement_init_zero               {0, 0}
#define VoltageDeltaMeasurement_init_zero        {0}
#define CurrentDeltaMeasurement_init_zero        {0}
#define VoltageMeasurement_init_zero             {0}
#define CurrentMeasurement_init_zero             {0}
#define PowerDeltaEntry_init_zero                {0, 0, 0}
#define PowerMeasurementDelta_init_zero          {0, 0}
#define RepeatedPowerDeltas_init_zero            {0, 0, {{NULL}, NULL}}
#define Teros12Measurement_init_zero             {0, 0, 0, 0}
#define Teros21Measurement_init_zero             {0, 0}
#define Phytos31Measurement_init_zero            {0, 0}
#define BME280Measurement_init_zero              {0, 0, 0}
#define SEN0308Measurement_init_zero             {0, 0}
#define SEN0257Measurement_init_zero             {0, 0}
#define YFS210CMeasurement_init_zero             {0}
#define PCAP02Measurement_init_zero              {0}
#define Measurement_init_zero                    {false, MeasurementMetadata_init_zero, 0, {PowerMeasurement_init_zero}}
#define Response_init_zero                       {_Response_ResponseType_MIN}
#define adcValue_init_zero                       {0}

/* Field tags (for use in manual encoding/decoding) */
#define MeasurementMetadata_cell_id_tag          1
#define MeasurementMetadata_logger_id_tag        2
#define MeasurementMetadata_ts_tag               3
#define PowerMeasurement_voltage_tag             2
#define PowerMeasurement_current_tag             3
#define VoltageDeltaMeasurement_voltage_tag      1
#define CurrentDeltaMeasurement_current_tag      1
#define VoltageMeasurement_voltage_tag           1
#define CurrentMeasurement_current_tag           1
#define PowerDeltaEntry_ts_tag                   1
#define PowerDeltaEntry_voltage_delta_tag        2
#define PowerDeltaEntry_current_delta_tag        3
#define PowerMeasurementDelta_voltage_delta_tag  2
#define PowerMeasurementDelta_current_delta_tag  3
#define RepeatedPowerDeltas_logger_id_tag        1
#define RepeatedPowerDeltas_cell_id_tag          2
#define RepeatedPowerDeltas_entries_tag          3
#define Teros12Measurement_vwc_raw_tag           2
#define Teros12Measurement_vwc_adj_tag           3
#define Teros12Measurement_temp_tag              4
#define Teros12Measurement_ec_tag                5
#define Teros21Measurement_matric_pot_tag        1
#define Teros21Measurement_temp_tag              2
#define Phytos31Measurement_voltage_tag          1
#define Phytos31Measurement_leaf_wetness_tag     2
#define BME280Measurement_pressure_tag           1
#define BME280Measurement_temperature_tag        2
#define BME280Measurement_humidity_tag           3
#define SEN0308Measurement_voltage_tag           1
#define SEN0308Measurement_humidity_tag          2
#define SEN0257Measurement_voltage_tag           1
#define SEN0257Measurement_pressure_tag          2
#define YFS210CMeasurement_flow_tag              1
#define PCAP02Measurement_capacitance_tag        1
#define Measurement_meta_tag                     1
#define Measurement_power_tag                    2
#define Measurement_teros12_tag                  3
#define Measurement_phytos31_tag                 4
#define Measurement_bme280_tag                   5
#define Measurement_teros21_tag                  6
#define Measurement_sen0308_tag                  7
#define Measurement_sen0257_tag                  8
#define Measurement_yfs210c_tag                  9
#define Measurement_pcap02_tag                   10
#define Response_resp_tag                        1
#define adcValue_adc_tag                         1

/* Struct field encoding specification for nanopb */
#define MeasurementMetadata_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   cell_id,           1) \
X(a, STATIC,   SINGULAR, UINT32,   logger_id,         2) \
X(a, STATIC,   SINGULAR, UINT32,   ts,                3)
#define MeasurementMetadata_CALLBACK NULL
#define MeasurementMetadata_DEFAULT NULL

#define PowerMeasurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   voltage,           2) \
X(a, STATIC,   SINGULAR, DOUBLE,   current,           3)
#define PowerMeasurement_CALLBACK NULL
#define PowerMeasurement_DEFAULT NULL

#define VoltageDeltaMeasurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   voltage,           1)
#define VoltageDeltaMeasurement_CALLBACK NULL
#define VoltageDeltaMeasurement_DEFAULT NULL

#define CurrentDeltaMeasurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   current,           1)
#define CurrentDeltaMeasurement_CALLBACK NULL
#define CurrentDeltaMeasurement_DEFAULT NULL

#define VoltageMeasurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   voltage,           1)
#define VoltageMeasurement_CALLBACK NULL
#define VoltageMeasurement_DEFAULT NULL

#define CurrentMeasurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   current,           1)
#define CurrentMeasurement_CALLBACK NULL
#define CurrentMeasurement_DEFAULT NULL

#define PowerDeltaEntry_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ts,                1) \
X(a, STATIC,   SINGULAR, UINT32,   voltage_delta,     2) \
X(a, STATIC,   SINGULAR, UINT32,   current_delta,     3)
#define PowerDeltaEntry_CALLBACK NULL
#define PowerDeltaEntry_DEFAULT NULL

#define PowerMeasurementDelta_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   voltage_delta,     2) \
X(a, STATIC,   SINGULAR, UINT32,   current_delta,     3)
#define PowerMeasurementDelta_CALLBACK NULL
#define PowerMeasurementDelta_DEFAULT NULL

#define RepeatedPowerDeltas_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   logger_id,         1) \
X(a, STATIC,   SINGULAR, UINT32,   cell_id,           2) \
X(a, CALLBACK, REPEATED, MESSAGE,  entries,           3)
#define RepeatedPowerDeltas_CALLBACK pb_default_field_callback
#define RepeatedPowerDeltas_DEFAULT NULL
#define RepeatedPowerDeltas_entries_MSGTYPE PowerDeltaEntry

#define Teros12Measurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   vwc_raw,           2) \
X(a, STATIC,   SINGULAR, DOUBLE,   vwc_adj,           3) \
X(a, STATIC,   SINGULAR, DOUBLE,   temp,              4) \
X(a, STATIC,   SINGULAR, UINT32,   ec,                5)
#define Teros12Measurement_CALLBACK NULL
#define Teros12Measurement_DEFAULT NULL

#define Teros21Measurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   matric_pot,        1) \
X(a, STATIC,   SINGULAR, DOUBLE,   temp,              2)
#define Teros21Measurement_CALLBACK NULL
#define Teros21Measurement_DEFAULT NULL

#define Phytos31Measurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   voltage,           1) \
X(a, STATIC,   SINGULAR, DOUBLE,   leaf_wetness,      2)
#define Phytos31Measurement_CALLBACK NULL
#define Phytos31Measurement_DEFAULT NULL

#define BME280Measurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   pressure,          1) \
X(a, STATIC,   SINGULAR, INT32,    temperature,       2) \
X(a, STATIC,   SINGULAR, UINT32,   humidity,          3)
#define BME280Measurement_CALLBACK NULL
#define BME280Measurement_DEFAULT NULL

#define SEN0308Measurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   voltage,           1) \
X(a, STATIC,   SINGULAR, DOUBLE,   humidity,          2)
#define SEN0308Measurement_CALLBACK NULL
#define SEN0308Measurement_DEFAULT NULL

#define SEN0257Measurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   voltage,           1) \
X(a, STATIC,   SINGULAR, DOUBLE,   pressure,          2)
#define SEN0257Measurement_CALLBACK NULL
#define SEN0257Measurement_DEFAULT NULL

#define YFS210CMeasurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   flow,              1)
#define YFS210CMeasurement_CALLBACK NULL
#define YFS210CMeasurement_DEFAULT NULL

#define PCAP02Measurement_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, DOUBLE,   capacitance,       1)
#define PCAP02Measurement_CALLBACK NULL
#define PCAP02Measurement_DEFAULT NULL

#define Measurement_FIELDLIST(X, a) \
X(a, STATIC,   OPTIONAL, MESSAGE,  meta,              1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (measurement,power,measurement.power),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (measurement,teros12,measurement.teros12),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (measurement,phytos31,measurement.phytos31),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (measurement,bme280,measurement.bme280),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (measurement,teros21,measurement.teros21),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (measurement,sen0308,measurement.sen0308),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (measurement,sen0257,measurement.sen0257),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (measurement,yfs210c,measurement.yfs210c),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (measurement,pcap02,measurement.pcap02),  10)
#define Measurement_CALLBACK NULL
#define Measurement_DEFAULT NULL
#define Measurement_meta_MSGTYPE MeasurementMetadata
#define Measurement_measurement_power_MSGTYPE PowerMeasurement
#define Measurement_measurement_teros12_MSGTYPE Teros12Measurement
#define Measurement_measurement_phytos31_MSGTYPE Phytos31Measurement
#define Measurement_measurement_bme280_MSGTYPE BME280Measurement
#define Measurement_measurement_teros21_MSGTYPE Teros21Measurement
#define Measurement_measurement_sen0308_MSGTYPE SEN0308Measurement
#define Measurement_measurement_sen0257_MSGTYPE SEN0257Measurement
#define Measurement_measurement_yfs210c_MSGTYPE YFS210CMeasurement
#define Measurement_measurement_pcap02_MSGTYPE PCAP02Measurement

#define Response_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    resp,              1)
#define Response_CALLBACK NULL
#define Response_DEFAULT NULL

#define adcValue_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   adc,               1)
#define adcValue_CALLBACK NULL
#define adcValue_DEFAULT NULL

extern const pb_msgdesc_t MeasurementMetadata_msg;
extern const pb_msgdesc_t PowerMeasurement_msg;
extern const pb_msgdesc_t VoltageDeltaMeasurement_msg;
extern const pb_msgdesc_t CurrentDeltaMeasurement_msg;
extern const pb_msgdesc_t VoltageMeasurement_msg;
extern const pb_msgdesc_t CurrentMeasurement_msg;
extern const pb_msgdesc_t PowerDeltaEntry_msg;
extern const pb_msgdesc_t PowerMeasurementDelta_msg;
extern const pb_msgdesc_t RepeatedPowerDeltas_msg;
extern const pb_msgdesc_t Teros12Measurement_msg;
extern const pb_msgdesc_t Teros21Measurement_msg;
extern const pb_msgdesc_t Phytos31Measurement_msg;
extern const pb_msgdesc_t BME280Measurement_msg;
extern const pb_msgdesc_t SEN0308Measurement_msg;
extern const pb_msgdesc_t SEN0257Measurement_msg;
extern const pb_msgdesc_t YFS210CMeasurement_msg;
extern const pb_msgdesc_t PCAP02Measurement_msg;
extern const pb_msgdesc_t Measurement_msg;
extern const pb_msgdesc_t Response_msg;
extern const pb_msgdesc_t adcValue_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define MeasurementMetadata_fields &MeasurementMetadata_msg
#define PowerMeasurement_fields &PowerMeasurement_msg
#define VoltageDeltaMeasurement_fields &VoltageDeltaMeasurement_msg
#define CurrentDeltaMeasurement_fields &CurrentDeltaMeasurement_msg
#define VoltageMeasurement_fields &VoltageMeasurement_msg
#define CurrentMeasurement_fields &CurrentMeasurement_msg
#define PowerDeltaEntry_fields &PowerDeltaEntry_msg
#define PowerMeasurementDelta_fields &PowerMeasurementDelta_msg
#define RepeatedPowerDeltas_fields &RepeatedPowerDeltas_msg
#define Teros12Measurement_fields &Teros12Measurement_msg
#define Teros21Measurement_fields &Teros21Measurement_msg
#define Phytos31Measurement_fields &Phytos31Measurement_msg
#define BME280Measurement_fields &BME280Measurement_msg
#define SEN0308Measurement_fields &SEN0308Measurement_msg
#define SEN0257Measurement_fields &SEN0257Measurement_msg
#define YFS210CMeasurement_fields &YFS210CMeasurement_msg
#define PCAP02Measurement_fields &PCAP02Measurement_msg
#define Measurement_fields &Measurement_msg
#define Response_fields &Response_msg
#define adcValue_fields &adcValue_msg

/* Maximum encoded size of messages (where known) */
/* RepeatedPowerDeltas_size depends on runtime parameters */
#define BME280Measurement_size                   23
#define CurrentDeltaMeasurement_size             6
#define CurrentMeasurement_size                  9
#define MEASUREMENTS_PB_H_MAX_SIZE               Measurement_size
#define MeasurementMetadata_size                 18
#define Measurement_size                         55
#define PCAP02Measurement_size                   9
#define Phytos31Measurement_size                 18
#define PowerDeltaEntry_size                     18
#define PowerMeasurementDelta_size               12
#define PowerMeasurement_size                    18
#define Response_size                            2
#define SEN0257Measurement_size                  18
#define SEN0308Measurement_size                  18
#define Teros12Measurement_size                  33
#define Teros21Measurement_size                  18
#define VoltageDeltaMeasurement_size             6
#define VoltageMeasurement_size                  9
#define YFS210CMeasurement_size                  9
#define adcValue_size                            6

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
